name: ONLYOFFICE Document Server
version: 8.2
slug: onlyoffice-docs
url: https://github.com/amaciuc/hassio-addons/tree/main/onlyoffice-docs
description: >-
  ONLYOFFICE Document Server is an online office suite comprising viewers and editors for texts, spreadsheets and presentations, fully compatible with Office Open XML formats: .docx, .xlsx, .pptx and enabling collaborative editing in real time.
arch:
  - amd64
  - aarch64
startup: services
init: false
ports:
  80/tcp: null
# map:
#   - type: addon_config
#     read_only: false
#     path: /etc/onlyoffice
environment:
  JWT_ENABLED: "true"
  JWT_SECRET: "a299c86a_jwt_onlyoffice"
  DB_TYPE: mariadb
  DB_HOST: core-mariadb
  DB_PORT: 3306
  DB_NAME: onlyoffice
  DB_USER: onlyoffice_user
  DB_PWD: onlyoffice_pwd
  REDIS_SERVER_HOST: a299c86a-redis-stack
  REDIS_SERVER_PORT: 6379
image: docker.io/onlyoffice/documentserver
